//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMapperexapem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Customer_DataEntities : DbContext
    {
        public Customer_DataEntities()
            : base("name=Customer_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionLog> ActionLogs { get; set; }
        public virtual DbSet<Feed> Feeds { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CustomersBackup_2017> CustomersBackup_2017 { get; set; }
        public virtual DbSet<CustomersBackup2017> CustomersBackup2017 { get; set; }
        public virtual DbSet<SareeDetail> SareeDetails { get; set; }
    }
}
